### ISSUE TITLE
Make Point,Polygon,Polyline not final classes

### ISSUE THREAD

**Issue by mraad** [Esri/geometry-api-java#101]
This will enable us to extent the class for another frameworks

**Comment by snodnipper** [comment]
Perhaps you'd like to wrap these geometries.

For example:

```
public class MyPoint {
     private Point mEsriPoint;
     public final double getX() { {
         return mEsriPoint.getX();
    }
}
```

That is similar to how we'd work with, say, [String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html), [Float](https://docs.oracle.com/javase/8/docs/api/java/lang/Float.html), [Double](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html) classes rather than extending them.  You can read more about 'favoring composition over inheritance' in [Effective Java, p.81](http://www.amazon.com/Effective-Java-2nd-Joshua-Bloch/dp/0321356683/).
