### ISSUE TITLE
Polygon Equals Fails: to and from GeoJSON

### ISSUE THREAD

**Issue by snodnipper** [Esri/geometry-api-java#84]
Creating a polygon, converting to GeoJSON and creating a new polygon from that GeoJSON creates objects that fail the .equals() contract.

String comparison works.

It fails in [AttributeStreamOfInt8.java][1]

```
    @Test
    public void polygon2PolygonFails() throws IOException, JSONException {
        OperatorFactoryLocal factory = OperatorFactoryLocal.getInstance();
        OperatorExportToGeoJson exporter = (OperatorExportToGeoJson) factory.getOperator(Operator.Type.ExportToGeoJson);
        String result = exporter.execute(birmingham());

        OperatorImportFromGeoJson importer = (OperatorImportFromGeoJson) factory.getOperator(Operator.Type.ImportFromGeoJson);
        MapGeometry mapGeometry = importer.execute(GeoJsonImportFlags.geoJsonImportDefaults, Geometry.Type.Polygon, result, null);
        Polygon polygon = (Polygon) mapGeometry.getGeometry();
        assertEquals(birmingham(), polygon);
    }

    @Test
    public void polygon2PolygonFails2() throws JSONException {
        String birminghamGeojson = GeometryEngine.geometryToGeoJson(birmingham());
        MapGeometry returnedGeometry = GeometryEngine.geometryFromGeoJson(birminghamGeojson,
                GeoJsonImportFlags.geoJsonImportDefaults, Geometry.Type.Polygon);
        Polygon polygon = (Polygon) returnedGeometry.getGeometry();
        assertEquals(polygon, birmingham());
    }

    @Test
    public void polygon2PolygonWorks() throws JSONException {
        String birminghamGeojson = GeometryEngine.geometryToGeoJson(birmingham());
        MapGeometry returnedGeometry = GeometryEngine.geometryFromGeoJson(birminghamGeojson,
                GeoJsonImportFlags.geoJsonImportDefaults, Geometry.Type.Polygon);
        Polygon polygon = (Polygon) returnedGeometry.getGeometry();
        assertEquals(polygon.toString(), birmingham().toString());
    }

    @Test
    public void polygon2Polygon2Works() throws JSONException, IOException {
        String birminghamJson = GeometryEngine.geometryToJson(4326, birmingham());
        MapGeometry returnedGeometry = GeometryEngine.jsonToGeometry(birminghamJson);
        Polygon polygon = (Polygon) returnedGeometry.getGeometry();
        assertEquals(polygon, birmingham());
    }

    public static Polygon birmingham() {
        return create(-1.954245, 52.513531, -1.837357, 52.450123);
    }

```

[1]: https://github.com/Esri/geometry-api-java/blob/master/src/main/java/com/esri/core/geometry/AttributeStreamOfInt8.java#L325

**Comment by stolstov** [comment]
@snodnipper Thanks for reporting this. We need to skip comparison of path_flags in equals for polygons.

Regardless, to ensure that equals() works as you expect before and after the export/import for any format, "normalize" geometry for this format by performing import/export on it. Repeated import/export calls should be producing identical geometries (at least on the same platform, as we rely on compiler's text to-number parsers). 
Esri shape and REST json importers and exporters are better as they represent the structure of Esri geometry as is (we may decide to delete empty or single point rings on import though).

The GeoJSON and OGC formats are not native to Esri geometry. Esri geometry does not distinguish between MULTIPOLYGON and POLYGON type because it is not needed for drawing or processing purposes. We import both into Esri Polygon type by copying rings only in the same order as they are stored in the original GeoJSON. To improve compatibility, when MULTIPOLYGON or POLYGON is imported from GeoJSON or OGC format, the first ring of each Polygon is marked with a flag in the path flags array. Export to GeoJSON or WKT will read the flags and separate group of rings into POLYGON's of MULTIPOLYGON. When flags are not set, we use ring area instead. That path_flags array is causing this bug.
